CREATE DATABASE BACKOFFICE;
CREATE DATABASE IDENTITY;
CREATE DATABASE FINANCEIRO;
CREATE DATABASE CONTROLEISCA;
CREATE DATABASE CONTROLEPATIO;

\c backoffice;

CREATE USER backoffice WITH PASSWORD 'Test@1234';
GRANT CONNECT ON DATABASE BACKOFFICE TO backoffice;
GRANT USAGE ON SCHEMA public TO backoffice;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO backoffice;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO backoffice;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO backoffice;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO backoffice;

CREATE TABLE IF NOT EXISTS TB_EMPRESAS (
	ID_EMPRESA SERIAL,
	NOME_FANTASIA VARCHAR (150) NOT NULL,
	RAZAO_SOCIAL VARCHAR (150) NOT NULL,
	CNPJ_CPF CHAR (14) NOT NULL,
    CODIGO INT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TB_EMPRESAS PRIMARY KEY (ID_EMPRESA)
);

CREATE INDEX IDX_TB_EMPRESAS_CNPJ_CPF ON TB_EMPRESAS (CNPJ_CPF);

CREATE TABLE IF NOT EXISTS TB_EMPRESA_ENDERECOS(
	ID_EMPRESA_ENDERECO SERIAL,
	ID_EMPRESA INT NOT NULL,
	CEP CHAR (8) NULL,
	RUA VARCHAR (80) NOT NULL,
	NUMERO VARCHAR (50) NULL,
	COMPLEMENTO VARCHAR (50) NULL,
	UF CHAR (2) NOT NULL,
	CIDADE VARCHAR (80) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_EMPRESA_ENDERECOS PRIMARY KEY (ID_EMPRESA_ENDERECO),
	CONSTRAINT FK_TB_EMPRESA_ENDERECOS_TB_EMPRESAS FOREIGN KEY (ID_EMPRESA)
        REFERENCES TB_EMPRESAS (ID_EMPRESA) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_EMPRESA_ENDERECOS_ID_EMPRESA ON TB_EMPRESA_ENDERECOS (ID_EMPRESA);

CREATE TABLE IF NOT EXISTS TB_EMPRESA_TELEFONES(
	ID_EMPRESA_TELEFONE SERIAL,
	ID_EMPRESA INT NOT NULL,
	TELEFONE VARCHAR (11) NOT NULL,
	DDD VARCHAR (5) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_EMPRESA_TELEFONES PRIMARY KEY (ID_EMPRESA_TELEFONE),
	CONSTRAINT FK_TB_EMPRESA_TELEFONES_TB_EMPRESAS FOREIGN KEY (ID_EMPRESA)
        REFERENCES TB_EMPRESAS (ID_EMPRESA) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_EMPRESA_TELEFONES_ID_EMPRESA ON TB_EMPRESA_TELEFONES (ID_EMPRESA);

CREATE TABLE IF NOT EXISTS TB_EMPRESA_EMAILS(
	ID_EMPRESA_TELEFONE SERIAL,
	ID_EMPRESA INT NOT NULL,
	EMAIL VARCHAR (100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_EMPRESA_EMAILS PRIMARY KEY (ID_EMPRESA_TELEFONE),
	CONSTRAINT FK_TB_EMPRESA_EMAILS_TB_EMPRESAS FOREIGN KEY (ID_EMPRESA)
        REFERENCES TB_EMPRESAS (ID_EMPRESA) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_EMPRESA_EMAILS_ID_EMPRESA ON TB_EMPRESA_EMAILS (ID_EMPRESA);

CREATE TABLE IF NOT EXISTS TB_CLIENTES (
    ID_CLIENTE SERIAL,
    ID_EMPRESA INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TB_CLIENTES PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT FK_TB_CLIENTES_TB_EMPRESAS FOREIGN KEY (ID_EMPRESA)
        REFERENCES TB_EMPRESAS (ID_EMPRESA) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_CLIENTES_ID_EMPRESA ON TB_CLIENTES (ID_EMPRESA);

CREATE TABLE IF NOT EXISTS TB_OPERACOES (
    ID_OPERACAO SERIAL,
    ID_CLIENTE INT NOT NULL,
    NOME VARCHAR (50) NOT NULL,
    DESCRICAO VARCHAR (200) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TB_OPERACOES PRIMARY KEY (ID_OPERACAO),
    CONSTRAINT FK_TB_OPERACOES_TB_CLIENTES FOREIGN KEY (ID_CLIENTE) 
        REFERENCES TB_CLIENTES (ID_CLIENTE) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_OPERACOES_ID_CLIENTE ON TB_OPERACOES (ID_CLIENTE);

CREATE TABLE IF NOT EXISTS TB_LOCAIS (
    ID_LOCAL SERIAL,
    ID_CLIENTE INT NOT NULL,
    NOME VARCHAR (50) NOT NULL,
    CEP CHAR (8) NULL,
	CIDADE VARCHAR (50) NULL,
	RUA VARCHAR (50) NULL,
	UF CHAR (2) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TB_LOCAIS PRIMARY KEY (ID_LOCAL),
    CONSTRAINT FK_TB_LOCAIS_TB_CLIENTES FOREIGN KEY (ID_CLIENTE) 
        REFERENCES TB_CLIENTES (ID_CLIENTE) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_LOCAIS_ID_CLIENTE ON TB_LOCAIS (ID_CLIENTE);

\c identity;

CREATE USER identity WITH PASSWORD 'Test@1234';
GRANT CONNECT ON DATABASE IDENTITY TO identity;
GRANT USAGE ON SCHEMA public TO identity;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO identity;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO identity;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO identity;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO identity;

CREATE TABLE IF NOT EXISTS TB_USUARIOS (
	ID_USUARIO SERIAL,
	NOME VARCHAR (150) NOT NULL,
	SENHA_HASH TEXT NOT NULL,
	SENHA_SALT TEXT  NOT NULL,
	IS_SUPERUSER BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TB_USUARIOS PRIMARY KEY (ID_USUARIO)
);

CREATE INDEX IDX_TB_USUARIOS_NOME ON TB_USUARIOS (NOME);

CREATE TABLE IF NOT EXISTS TB_PERFIS (
	ID_PERFIL SERIAL,
	ID_USUARIO INT NOT NULL,
    FOTO VARCHAR (250) NULL,
	EMAIL VARCHAR (100) NULL,
	RECEBE_EMAIL BOOLEAN NOT NULL DEFAULT FALSE,
	TELEFONE VARCHAR (11) NULL,
	DDD VARCHAR (5) NULL,
    CARGO VARCHAR (50) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(), 
    CONSTRAINT PK_TB_PERFIS PRIMARY KEY (ID_PERFIL),
    CONSTRAINT FK_TB_PERFIS_TB_USUARIOS FOREIGN KEY (ID_USUARIO)
        REFERENCES TB_USUARIOS (ID_USUARIO) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_PERFIS_ID_USUARIO ON TB_PERFIS (ID_USUARIO);

CREATE TABLE IF NOT EXISTS TB_SISTEMAS (
	ID_SISTEMA SERIAL,
	NOME VARCHAR (150) NOT NULL,
	CLIENTE BOOLEAN NOT NULL DEFAULT FALSE,
	LOCAL BOOLEAN NOT NULL DEFAULT FALSE,
	OPERACAO BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_SISTEMAS PRIMARY KEY (ID_SISTEMA)
);

CREATE INDEX IDX_TB_SISTEMAS_NOME ON TB_SISTEMAS (NOME);

CREATE TABLE IF NOT EXISTS TB_ACESSOS (
	ID_ACESSO SERIAL,
	ID_USUARIO INT NOT NULL,
	ID_SISTEMA INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_ACESSOS PRIMARY KEY (ID_ACESSO),
    CONSTRAINT FK_TB_ACESSOS_TB_USUARIOS FOREIGN KEY (ID_USUARIO)
        REFERENCES TB_USUARIOS (ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_TB_ACESSOS_TB_SISTEMAS FOREIGN KEY (ID_SISTEMA)
        REFERENCES TB_SISTEMAS (ID_SISTEMA) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_ACESSOS_ID_USUARIO ON TB_ACESSOS (ID_USUARIO);
CREATE INDEX IDX_TB_ACESSOS_ID_SISTEMA ON TB_ACESSOS (ID_SISTEMA);

CREATE TABLE IF NOT EXISTS TB_PERMISSOES (
	ID_PERMISSAO SERIAL,
	ID_ACESSO INT NOT NULL,
	READ BOOLEAN NOT NULL DEFAULT TRUE,
	WRITE BOOLEAN NOT NULL DEFAULT FALSE,
	REMOVE BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_PERMISSOES PRIMARY KEY (ID_PERMISSAO),
    CONSTRAINT FK_TB_PERMISSOES_TB_ACESSOS FOREIGN KEY (ID_ACESSO)
        REFERENCES TB_ACESSOS (ID_ACESSO) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_PERMISSOES_ID_ACESSO ON TB_PERMISSOES (ID_ACESSO);

CREATE TABLE IF NOT EXISTS TB_ASSOCIADO_CLIENTES (
	ID_ASSOCIADO_CLIENTE SERIAL,
	ID_ACESSO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_ASSOCIADO_CLIENTES  PRIMARY KEY (ID_ASSOCIADO_CLIENTE),
    CONSTRAINT FK_TB_ASSOCIADO_CLIENTES_TB_ACESSOS FOREIGN KEY (ID_ACESSO)
        REFERENCES TB_ACESSOS (ID_ACESSO) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_ASSOCIADO_CLIENTES_ID_ACESSO ON TB_ASSOCIADO_CLIENTES (ID_ACESSO);

CREATE TABLE IF NOT EXISTS TB_ASSOCIADO_LOCAIS (
	ID_ASSOCIADO_LOCAL SERIAL,
	ID_ACESSO INT NOT NULL,
	ID_LOCAL INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_ASSOCIADO_LOCAIS PRIMARY KEY (ID_ASSOCIADO_LOCAL),
    CONSTRAINT FK_TB_ASSOCIADO_LOCAIS_TB_ACESSOS FOREIGN KEY (ID_ACESSO)
        REFERENCES TB_ACESSOS (ID_ACESSO) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_ASSOCIADO_LOCAIS_ID_ACESSO ON TB_ASSOCIADO_LOCAIS (ID_ACESSO);

CREATE TABLE IF NOT EXISTS TB_ASSOCIADO_OPERACOES (
	ID_ASSOCIADO_OPERACAO SERIAL,
	ID_ACESSO INT NOT NULL,
	ID_OPERACAO INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_ASSOCIADO_OPERACOES PRIMARY KEY (ID_ASSOCIADO_OPERACAO),
    CONSTRAINT FK_TB_ASSOCIADO_OPERACOES_TB_ACESSOS FOREIGN KEY (ID_ACESSO)
        REFERENCES TB_ACESSOS (ID_ACESSO) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_ASSOCIADO_OPERACOES_ID_ACESSO ON TB_ASSOCIADO_OPERACOES (ID_ACESSO);

\c financeiro;

CREATE USER financeiro WITH PASSWORD 'Test@1234';
GRANT CONNECT ON DATABASE FINANCEIRO TO financeiro;
GRANT USAGE ON SCHEMA public TO financeiro;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO financeiro;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO financeiro;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO financeiro;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO financeiro;

CREATE TABLE IF NOT EXISTS TB_CONTRATOS (
	ID_CONTRATO SERIAL,
	ID_CLIENTE INT NOT NULL,
	TIPO_CONTRATO VARCHAR (50) NULL,
	FORMA_PAGAMENTO VARCHAR (50) NULL,
	EMAIL VARCHAR (100) NULL,
    DATA_INICIO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_TERMINO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TB_CONTRATOS PRIMARY KEY (ID_CONTRATO)
);

CREATE INDEX IDX_TB_CONTRATOS_ID_CLIENTE ON TB_CONTRATOS (ID_CLIENTE);
CREATE INDEX IDX_TB_CONTRATOS_DATA_INICIO ON TB_CONTRATOS (DATA_INICIO);

CREATE TABLE IF NOT EXISTS TB_CONTATOS (
	ID_CONTATO SERIAL,
    NOME VARCHAR (50) NOT NULL,
    EMAIL VARCHAR (100) NOT NULL,
    TELEFONE VARCHAR (11) NULL,
	DDD VARCHAR (5) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_CONTATOS PRIMARY KEY (ID_CONTATO)
);

CREATE INDEX IDX_TB_CONTATOS_EMAIL ON TB_CONTATOS (EMAIL);

CREATE TABLE IF NOT EXISTS TB_GPO_CONTATOS (
	ID_GPO_CONTATO SERIAL,
    ID_CONTATO INT NOT NULL,
    TITULO VARCHAR (50) NOT NULL,
    DESCRICAO VARCHAR (250) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TB_GPO_CONTATOS PRIMARY KEY (ID_GPO_CONTATO),
    CONSTRAINT FK_TB_GPO_CONTATOS_TB_CONTATOS FOREIGN KEY (ID_CONTATO)
        REFERENCES TB_CONTATOS (ID_CONTATO) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_GPO_CONTATOS_ID_CONTATO ON TB_GPO_CONTATOS (ID_CONTATO);

CREATE TABLE IF NOT EXISTS TB_CONTRATOS_GPO_CONTATOS (
	ID_CONTRATO_GPO_CONTATO SERIAL,
    ID_GPO_CONTATO INT NOT NULL,
    ID_CONTRATO INT NOT NULL,
    CC BOOLEAN NOT NULL DEFAULT TRUE,
    DESCRICAO VARCHAR (250) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_CONTRATOS_GPO_CONTATOS PRIMARY KEY (ID_CONTRATO_GPO_CONTATO),
    CONSTRAINT FK_TB_CONTRATOS_GPO_CONTATOS_TB_GPO_CONTATOS FOREIGN KEY (ID_GPO_CONTATO)
        REFERENCES TB_GPO_CONTATOS (ID_GPO_CONTATO) ON DELETE CASCADE,
    CONSTRAINT FK_TB_CONTRATOS_GPO_CONTATOS_TB_CONTRATOS FOREIGN KEY (ID_CONTRATO)
        REFERENCES TB_CONTRATOS (ID_CONTRATO) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_CONTRATOS_GPO_CONTATOS_ID_CONTRATO ON TB_CONTRATOS_GPO_CONTATOS (ID_CONTRATO);

CREATE TABLE IF NOT EXISTS TB_PENDENCIAS (
	ID_PENDENCIA SERIAL,
	ID_CONTRATO INT NOT NULL,
	COMPETENCIA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ENVIO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_INICIO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_TERMINO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR (100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TB_PENDENCIAS PRIMARY KEY (ID_PENDENCIA),
    CONSTRAINT FK_TB_PENDENCIAS_TB_CONTRATOS FOREIGN KEY (ID_CONTRATO)
        REFERENCES TB_CONTRATOS (ID_CONTRATO) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_PENDENCIAS_ID_CONTRATO ON TB_PENDENCIAS (ID_CONTRATO);
CREATE INDEX IDX_TB_PENDENCIAS_STATUS ON TB_PENDENCIAS (STATUS);

CREATE TABLE IF NOT EXISTS TB_RELATORIOS (
	ID_RELATORIO SERIAL,
	ID_PENDENCIA INT NOT NULL,
	ANEXO VARCHAR (250) NOT NULL,
    TITULO VARCHAR (50) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_RELATORIOS PRIMARY KEY (ID_RELATORIO),
    CONSTRAINT FK_TB_RELATORIOS_TB_PENDENCIAS FOREIGN KEY (ID_PENDENCIA)
        REFERENCES TB_PENDENCIAS (ID_PENDENCIA) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_RELATORIOS_ID_PENDENCIA ON TB_RELATORIOS (ID_PENDENCIA);

CREATE TABLE IF NOT EXISTS TB_BOLETOS (
	ID_BOLETO SERIAL,
	ID_PENDENCIA INT NOT NULL,
	ANEXO VARCHAR (250) NOT NULL,
    TITULO VARCHAR (50) NULL,
    VALOR DECIMAL (10,2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_BOLETOS PRIMARY KEY (ID_BOLETO),
    CONSTRAINT FK_TB_BOLETOS_TB_PENDENCIA FOREIGN KEY (ID_PENDENCIA)
        REFERENCES TB_PENDENCIAS (ID_PENDENCIA) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_BOLETOS_ID_PENDENCIA ON TB_BOLETOS (ID_PENDENCIA);

CREATE TABLE IF NOT EXISTS TB_NFS (
	ID_NF SERIAL,
	ID_PENDENCIA INT NOT NULL,
	ANEXO VARCHAR (250) NOT NULL,
    TITULO VARCHAR (50) NULL,
    VALOR DECIMAL (10,2) NOT NULL,
    NUMERO VARCHAR (100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_NFS PRIMARY KEY (ID_NF),
    CONSTRAINT FK_TB_NFS_TB_PENDENCIAS FOREIGN KEY (ID_PENDENCIA)
        REFERENCES TB_PENDENCIAS (ID_PENDENCIA) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_NFS_ID_PENDENCIA ON TB_NFS (ID_PENDENCIA);

\c controleisca;

CREATE USER controleisca WITH PASSWORD 'Test@1234';
GRANT CONNECT ON DATABASE CONTROLEISCA TO controleisca;
GRANT USAGE ON SCHEMA public TO controleisca;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO controleisca;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO controleisca;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO controleisca;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO controleisca;

CREATE TABLE IF NOT EXISTS TB_TECNOLOGIAS (
    ID_TECNOLOGIA SERIAL,
    NOME VARCHAR (50) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TB_TECNOLOGIAS PRIMARY KEY (ID_TECNOLOGIA)
);

CREATE INDEX IDX_TB_TECNOLOGIAS_NOME ON TB_TECNOLOGIAS (NOME);

CREATE TABLE IF NOT EXISTS TB_LOCALIZACOES (
    ID_LOCALIZACAO SERIAL,
    ID_TECNOLOGIA INT NOT NULL,
    ODOMETRO BIGINT NOT NULL DEFAULT 0,
    LATITUDE DECIMAL(9,6) NOT NULL DEFAULT 0,
    LONGITUDE DECIMAL(9,6) NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_LOCALIZACOES PRIMARY KEY (ID_LOCALIZACAO),
    CONSTRAINT FK_TB_LOCALIZACOES_TB_TECNOLOGIAS FOREIGN KEY (ID_TECNOLOGIA)
        REFERENCES TB_TECNOLOGIAS (ID_TECNOLOGIA) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_LOCALIZACOES_ID_TECNOLOGIA ON TB_LOCALIZACOES (ID_TECNOLOGIA);

CREATE TABLE IF NOT EXISTS TB_ISCAS (
	ID_ISCA SERIAL,
	ID_OPERACAO INT NOT NULL,
    ID_LOCAL INT NOT NULL,
	ID_USUARIO INT NOT NULL,
    ID_TECNOLOGIA INT NOT NULL,
    COGIDO INT NOT NULL,
    STATUS VARCHAR (50) NOT NULL,
    COMUNICACAO VARCHAR (50) NOT NULL,
    MODELO VARCHAR (50) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TB_ISCAS PRIMARY KEY (ID_ISCA),
    CONSTRAINT FK_TB_ISCAS_TB_TECNOLOGIAS FOREIGN KEY (ID_TECNOLOGIA)
        REFERENCES TB_TECNOLOGIAS (ID_TECNOLOGIA) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_ISCAS_STATUS ON TB_ISCAS (STATUS);
CREATE INDEX IDX_TB_ISCAS_ID_OPERACAO ON TB_ISCAS (ID_OPERACAO);
CREATE INDEX IDX_TB_ISCAS_ID_LOCAL ON TB_ISCAS (ID_LOCAL);

CREATE TABLE IF NOT EXISTS TB_ISCA_ANEXOS (
	ID_ISCA_ANEXO SERIAL,
    ID_ISCA INT NOT NULL,
    ANEXO VARCHAR (250) NOT NULL,
    TITULO VARCHAR (50) NOT NULL,
    DESCRICAO VARCHAR (250) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_ISCA_ANEXOS PRIMARY KEY (ID_ISCA_ANEXO),
    CONSTRAINT FK_TB_ISCA_ANEXOS_TB_ISCAS FOREIGN KEY (ID_ISCA)
        REFERENCES TB_ISCAS (ID_ISCA) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_ISCA_ANEXOS_ID_ISCA ON TB_ISCA_ANEXOS (ID_ISCA);

CREATE TABLE IF NOT EXISTS TB_ISCA_CHECKLISTS (
	ID_ISCA_CHECKLIST SERIAL,
    ID_ISCA INT NOT NULL,
    RESULTADO VARCHAR (50) NOT NULL,
    IMPLANTACAO BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TB_ISCA_CHECKLISTS  PRIMARY KEY (ID_ISCA_CHECKLIST),
    CONSTRAINT FK_TB_ISCA_CHECKLISTS_TB_ISCAS FOREIGN KEY (ID_ISCA)
        REFERENCES TB_ISCAS (ID_ISCA) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_ISCA_CHECKLISTS_ID_RESULTADO ON TB_ISCA_CHECKLISTS (RESULTADO);

CREATE TABLE IF NOT EXISTS TB_ISCA_FORMULARIOS (
	ID_ISCA_FORMULARIO SERIAL,
    ID_ISCA_CHECKLIST INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    ETAPA VARCHAR (50) NOT NULL,
    RESULTADO VARCHAR (50) NOT NULL,
    OBSERVACAO VARCHAR (250) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_ISCA_FORMULARIOS PRIMARY KEY (ID_ISCA_FORMULARIO),
    CONSTRAINT FK_TB_ISCA_FORMULARIOS_TB_ISCA_CHECKLISTS FOREIGN KEY (ID_ISCA_CHECKLIST)
        REFERENCES TB_ISCA_CHECKLISTS (ID_ISCA_CHECKLIST) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_ISCA_FORMULARIOS_ETAPA ON TB_ISCA_FORMULARIOS (ETAPA);
CREATE INDEX IDX_TB_ISCA_FORMULARIOS_ID_ISCA_CHECKLIST ON TB_ISCA_FORMULARIOS (ID_ISCA_CHECKLIST);

CREATE TABLE IF NOT EXISTS TB_RASTREAMENTOS (
	ID_RASTREAMENTO SERIAL,
    ID_ISCA INT NOT NULL,
    NUMERO_VIAGEM INT NOT NULL,
    MANIFESTO VARCHAR(100) NULL,
    VOLUME INT NULL,
    VALOR DECIMAL(12,2) NULL DEFAULT 0,
    ROTA_INSERCAO VARCHAR (100) NULL,
    ROTA_MAIOR_VALOR VARCHAR (100) NULL,
    PLACA VARCHAR (10) NULL,
    RESULTADO VARCHAR (50) NULL,
	DATA_IMPLANTACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_SAIDA TIMESTAMP NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TB_RASTREAMENTOS PRIMARY KEY (ID_RASTREAMENTO),
    CONSTRAINT FK_TB_RASTREAMENTOS_TB_ISCAS FOREIGN KEY (ID_ISCA)
        REFERENCES TB_ISCAS (ID_ISCA) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_RASTREAMENTOS_VALOR ON TB_RASTREAMENTOS (VALOR);
CREATE INDEX IDX_TB_RASTREAMENTOS_NUMERO_VIAGEM ON TB_RASTREAMENTOS (NUMERO_VIAGEM);

CREATE TABLE IF NOT EXISTS TB_RASTREAMENTO_ANEXOS (
	ID_RASTREAMENTO_ANEXO SERIAL,
    ID_RASTREAMENTO INT NOT NULL,
    ANEXO VARCHAR (250) NOT NULL,
    TITULO VARCHAR (50) NOT NULL,
    DESCRICAO VARCHAR (250) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_RASTREAMENTO_ANEXOS PRIMARY KEY (ID_RASTREAMENTO_ANEXO),
    CONSTRAINT FK_TB_RASTREAMENTO_ANEXOS_TB_RASTREAMENTOS FOREIGN KEY (ID_RASTREAMENTO)
        REFERENCES TB_RASTREAMENTOS (ID_RASTREAMENTO) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_RASTREAMENTO_ANEXOS_ID_RASTREAMENTO ON TB_RASTREAMENTO_ANEXOS (ID_RASTREAMENTO);

\c controlepatio;

CREATE USER controlepatio WITH PASSWORD 'Test@1234';
GRANT CONNECT ON DATABASE CONTROLEPATIO TO controlepatio;
GRANT USAGE ON SCHEMA public TO controlepatio;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO controlepatio;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO controlepatio;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO controlepatio;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO controlepatio;

CREATE TABLE IF NOT EXISTS TB_PATIO_LOCAIS (
    ID_PATIO_LOCAL SERIAL,
    ID_LOCAL INT NOT NULL,
    TEMPO_MINUTO INT NOT NULL DEFAULT 0 CHECK (TEMPO_MINUTO BETWEEN 0 AND 60),
    TEMPO_HORA INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TB_PATIO_LOCAIS PRIMARY KEY (ID_PATIO_LOCAL)
);

CREATE INDEX IDX_TB_PATIO_LOCAIS_ID_LOCAL ON TB_PATIO_LOCAIS (ID_LOCAL);

CREATE TABLE IF NOT EXISTS TB_PATIOS (
    ID_PATIO SERIAL,
    ID_PATIO_LOCAL INT NOT NULL,
    PLACA VARCHAR (10) NOT NULL,
    MOTORISTA VARCHAR (50) NOT NULL,
    DATA_CHEGADA DATE NULL,
    CHEGADA_MINUTO INT NOT NULL DEFAULT 0 CHECK (CHEGADA_MINUTO BETWEEN 0 AND 60),
    CHEGADA_HORA INT NOT NULL DEFAULT 0,
    DATA_SAIDA DATE NULL,
    SAIDA_MINUTO INT NOT NULL DEFAULT 0 CHECK (SAIDA_MINUTO BETWEEN 0 AND 60),
    SAIDA_HORA INT NOT NULL DEFAULT 0,
    TOTAL_MINUTO INT NOT NULL DEFAULT 0 CHECK (TOTAL_MINUTO BETWEEN 0 AND 60),
    TOTAL_HORA INT NOT NULL DEFAULT 0,
    INTERVALO_SAIDA_MINUTO INT NOT NULL DEFAULT 0 CHECK (INTERVALO_SAIDA_MINUTO BETWEEN 0 AND 60),
    INTERVALO_SAIDA_HORA INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TB_PATIOS PRIMARY KEY (ID_PATIO),
    CONSTRAINT FK_TB_PATIOS_TB_PATIO_LOCAIS FOREIGN KEY (ID_PATIO_LOCAL)
        REFERENCES TB_PATIO_LOCAIS (ID_PATIO_LOCAL) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_PATIOS_PLACA ON TB_PATIOS (PLACA);
CREATE INDEX IDX_TB_PATIOS_DATA_SAIDA ON TB_PATIOS (DATA_SAIDA);

CREATE TABLE IF NOT EXISTS TB_FASE_CONFIGS (
    ID_FASE_CONFIG SERIAL,
    ID_PATIO_LOCAL INT NOT NULL,
    NOME VARCHAR (50) NOT NULL,
    ORDEM INT NULL,
    TEMPO_MINUTO INT NOT NULL DEFAULT 0 CHECK (TEMPO_MINUTO BETWEEN 0 AND 60),
    TEMPO_HORA INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TB_FASE_CONFIGS PRIMARY KEY (ID_FASE_CONFIG),
    CONSTRAINT FK_TB_FASE_CONFIGS_TB_PATIO_LOCAIS FOREIGN KEY (ID_PATIO_LOCAL)
        REFERENCES TB_PATIO_LOCAIS (ID_PATIO_LOCAL) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_FASE_CONFIGS_NOME ON TB_FASE_CONFIGS (NOME);

CREATE TABLE IF NOT EXISTS TB_FASES (
    ID_FASE SERIAL,
    ID_FASE_CONFIG INT NOT NULL,
    DATA_APRESENTACAO DATE NULL,
    APRESENTACAO_MINUTO INT NOT NULL DEFAULT 0 CHECK (APRESENTACAO_MINUTO BETWEEN 0 AND 60),
    APRESENTACAO_HORA INT NOT NULL DEFAULT 0,
    DATA_INICIO DATE NULL,
    INICIO_MINUTO INT NOT NULL DEFAULT 0 CHECK (INICIO_MINUTO BETWEEN 0 AND 60),
    INICIO_HORA INT NOT NULL DEFAULT 0,
    DATA_FIM DATE NULL,
    FIM_MINUTO INT NOT NULL DEFAULT 0 CHECK (FIM_MINUTO BETWEEN 0 AND 60),
    FIM_HORA INT NOT NULL DEFAULT 0,
    INTERVALO_SAIDA_MINUTO INT NOT NULL DEFAULT 0 CHECK (INTERVALO_SAIDA_MINUTO BETWEEN 0 AND 60),
    INTERVALO_SAIDA_HORA INT NOT NULL DEFAULT 0,
    TOTAL_MINUTO INT NOT NULL DEFAULT 0 CHECK (TOTAL_MINUTO BETWEEN 0 AND 60),
    TOTAL_HORA INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_FASES PRIMARY KEY (ID_FASE),
    CONSTRAINT FK_TB_FASES_TB_FASE_CONFIGS FOREIGN KEY (ID_FASE_CONFIG)
        REFERENCES TB_FASE_CONFIGS (ID_FASE_CONFIG) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_FASES_DATA_INICIO ON TB_FASES (DATA_INICIO);
CREATE INDEX IDX_TB_FASES_DATA_FIM ON TB_FASES (DATA_FIM);

CREATE TABLE IF NOT EXISTS TB_FASE_OCORRENCIAS (
    ID_FASE_OCORRENCIA SERIAL,
    ID_FASE INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    TITULO VARCHAR (50) NULL,
    OBSERVACAO VARCHAR (250) NULL,
    HORARIO TIMESTAMP NOT NULL DEFAULT NOW(),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_TB_FASE_OCORRENCIAS PRIMARY KEY (ID_FASE_OCORRENCIA),
    CONSTRAINT FK_TB_FASE_OCORRENCIAS_TB_FASES FOREIGN KEY (ID_FASE)
        REFERENCES TB_FASES (ID_FASE) ON DELETE CASCADE
);

CREATE INDEX IDX_TB_FASE_OCORRENCIAS_HORARIO ON TB_FASE_OCORRENCIAS (HORARIO);
CREATE INDEX IDX_TB_FASE_OCORRENCIAS_ID_FASE ON TB_FASE_OCORRENCIAS (ID_FASE);